import Head from "next/head";
import AboutIndex from "./components/Home/About/index";
import Footer from "./components/Home/Landing Page/Footer";


export default function About () {
  return (
    <>
    <Head>
        <title>Panaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/panaverse1.png" />
      </Head>
    <AboutIndex/>
    <Footer/>
  </>
  );
};
