import { Box, chakra, Container,Text, Divider, Flex, Heading, Link, Stack } from "@chakra-ui/react";
import Head from "next/head";
import CoursesIndex from "./components/Home/Courses/CoursesIndex";
import Footer from "./components/Home/Landing Page/Footer";
import Navbar from "./components/Home/Landing Page/Navbar";

export default function Courses() {
  return (
      <>
      <Head>
        <title>Panaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/panaverse1.png" />
      </Head>

      <Navbar/>
      <CoursesIndex />


<Footer></Footer>
      
      </>
  );
}
