import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from './Navbar'
import Panaverse from './components/Home/Panaverse'
import Program from './components/Home/Program'
import Students from './components/Home/Students'
import Footer from './components/Home/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Panaverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/panaverse1.png" />
      </Head>
      
        <Navbar/>
        <Panaverse/>
        <Program/>
        <Students/>
        <Footer/>

       
    </>
  )
}
